# Generated by Django 5.1.4 on 2024-12-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_cart', to='store.clothes'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothes_photo',
            field=models.FileField(blank=True, null=True, upload_to='clothes_video/'),
        ),
        migrations.AlterField(
            model_name='color',
            name='clothes_connect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='store.clothes'),
        ),
    ]
