# Generated by Django 5.1.4 on 2024-12-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_quantity_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.clothes'),
            preserve_default=False,
        ),
    ]
