# Generated by Django 5.1.3 on 2024-12-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_favoriteitem_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='category_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
    ]
