# Generated by Django 5.1.4 on 2024-12-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_wear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wear',
        ),
    ]
