# Generated by Django 5.1.4 on 2024-12-21 10:38

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_wear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='clothes_connect',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wear',
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='store.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=1, max_length=17, verbose_name='размер'),
            preserve_default=False,
        ),
    ]
