# Generated by Django 5.1.4 on 2024-12-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_color_clothes_connect_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='color',
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.ManyToManyField(related_name='clothes', to='store.color'),
        ),
    ]
